[package]
name = "edgefirst-schemas"
description = "Message schemas for EdgeFirst Perception - ROS2 Common Interfaces, Foxglove, and custom types"
authors = ["Au-Zone Technologies <support@au-zone.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
version = "1.4.1"
homepage = "https://doc.edgefirst.ai"
repository = "https://github.com/EdgeFirstAI/schemas"
documentation = "https://docs.rs/edgefirst-schemas/"
keywords = ["ros2", "perception", "schemas", "edge-ai", "zenoh"]
categories = ["encoding", "data-structures"]

[dependencies]
serde = "1.0.219"
serde_derive = "1.0.219"
