[package]
name = "edgefirst-schemas"
description = "EdgeFirst Middleware Schemas"
authors = ["Au-Zone Technologies <support@au-zone.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
version = "0.0.0"
homepage = "https://studio.edgefirst.ai"
repository = "https://github.com/EdgeFirstAI/schemas"
documentation = "https://docs.rs/edgefirst-schemas/"

[dependencies]
serde = "1.0.219"
serde_derive = "1.0.219"
